---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS or Rocky Linux)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution in ["CentOS", "Rocky"]

  - name: install updates (Ubuntu or Debian)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]


- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php packages for Ubuntu or Debian servers
    tags: apache,apache2,ubuntu,debian
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: install apache and php packages for CentOS or Rocky Linux servers
    tags: apache,centos,rocky,httpd
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution in ["CentOS", "Rocky"]


- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (CentOS or Rocky Linux)
    tags: centos,db,mariadb,rocky
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution in ["CentOS", "Rocky"]

  - name: install mariadb package (Ubuntu or Debian)
    tags: ubuntu,debian,db,mariadb
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution in ["Ubuntu", "Debian"]


- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
