- name: install apache and php packages for Ubuntu or Debian servers
  tags: apache,apache2,ubuntu,debian
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: install apache and php packages for CentOS or Rocky Linux servers
  tags: apache,centos,rocky,httpd
  dnf:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution in ["CentOS", "Rocky"]

- name: start httpd (CentOS or Rocky Linux)
  tags: apache.centos,rocky,httpd
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution in ["CentOS", "Rocky"]

- name: change email address for admin
  tags: apache,centos,rocky,httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin admin@wynsoft.cloud
  when: ansible_distribution in ["CentOS", "Rocky"]
  register: httpd

- name: restart httpd (CentOS or Rocky Linux)
  tags: apache,apache2,httpd
  service:
    name: httpd
    state: restarted
  when: httpd.changed

- name: copy default html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
