- name: install mariadb package (CentOS or Rocky Linux)
  tags: centos,db,mariadb,rocky
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution in ["CentOS", "Rocky"]

- name: install mariadb package (Ubuntu or Debian)
  tags: ubuntu,debian,db,mariadb
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution in ["Ubuntu", "Debian"]
